# Generated by Django 3.1.2 on 2020-11-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerto',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
